@startuml

title Observer/Observable Design Patterns

interface Observer {
    void notify()
}

class ObserverManager {
    List<Observer> observers
    public void register(Observer observer)
    public void unregister(Observer observer)
    public void notifyObservers()
}
note left
    public void notifyObservers() {
        for (Observer observer : observers) {
            observer.notify();
        }
    }
end note
ObserverManager o- Observer

class Subject {
}
Subject -down-> ObserverManager : notifyObservers()

class ConcreteObserver1 implements Observer {
    public void notify()
}

class ConcreteObserver2 implements Observer {
    public void notify()
}

ConcreteObserver1 -> ObserverManager : register
ConcreteObserver2 -> ObserverManager : register

@enduml